# Generated by Django 6.1.1 on 2026-09-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_user_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname_style',
            field=models.CharField(choices=[('default', 'Обычный'), ('gold', 'Золотой градиент'), ('fire', 'Огненный'), ('ice', 'Ледяной'), ('blood', 'Кровавый'), ('emerald', 'Изумрудный'), ('royal', 'Королевский'), ('cosmic', 'Космический'), ('neon-pink', 'Неон розовый'), ('neon-blue', 'Неон голубой'), ('neon-green', 'Неон зелёный'), ('rainbow', 'Радужный (анимированный)')], default='default', max_length=20),
        ),
    ]
